name: Mirror to ethisnetwork

on:
  push:
    branches: ['**']

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push mirror
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_PAT }}@github.com/ethisnetwork/website-prod.git
          git push mirror --mirror
